/* eslint-disable */
/**
 * Stub generated by hand. Will be overwritten by `npx convex dev` with the
 * proper strongly-typed `api` / `internal` references discovered from
 * crawling `convex/*.ts`. For now, type each function with its actual
 * query/mutation/action kind so client `useQuery` / `useMutation` calls
 * typecheck at build time without the real codegen.
 */
import { FunctionReference } from "convex/server";

type AnyQuery = FunctionReference<"query", "public", any, any>;
type AnyMutation = FunctionReference<"mutation", "public", any, any>;
type AnyAction = FunctionReference<"action", "public", any, any>;

export declare const api: {
  words: {
    dueForReview: AnyQuery;
    listAll: AnyQuery;
    dueCount: AnyQuery;
    add: AnyMutation;
    recordReview: AnyMutation;
  };
  documents: {
    list: AnyQuery;
    getWithSentences: AnyQuery;
    create: AnyMutation;
  };
  seed: {
    run: AnyMutation;
  };
};

export declare const internal: Record<string, Record<string, AnyQuery | AnyMutation | AnyAction>>;
