/* eslint-disable */
/**
 * Stub generated by hand. Will be overwritten by `npx convex dev`.
 *
 * The post-codegen version of this file uses `anyApi` from convex/server to
 * build a Proxy that walks dotted paths into real FunctionReferences. We
 * mirror that behavior verbatim so `api.words.dueForReview` works at
 * runtime even before the first deployment.
 */
import { anyApi } from "convex/server";
export const api = anyApi;
export const internal = anyApi;
