/* eslint-disable */
/**
 * Stub generated by hand. Will be overwritten by `npx convex dev`.
 */
import { DataModelFromSchemaDefinition, DocumentByName, TableNamesInDataModel } from "convex/server";
import { GenericId } from "convex/values";
import schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type TableNames = TableNamesInDataModel<DataModel>;
export type Doc<TableName extends TableNames> = DocumentByName<DataModel, TableName>;
export type Id<TableName extends TableNames | string = TableNames | string> = GenericId<TableName>;
