/* eslint-disable */
/**
 * Stub generated by hand for build-time use BEFORE the first `npx convex dev` run.
 *
 * Once you run `npx convex dev`, Convex's codegen will overwrite this whole
 * `_generated/` directory with the real type-safe versions. Do not commit
 * the post-codegen variants — `.gitignore` excludes `convex/_generated/`,
 * so they stay local. This stub is the **only** file in here that is
 * committed; it gives `tsc` something to chew on for `next build` until
 * the real deployment exists.
 */
import {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  GenericQueryCtx,
  GenericMutationCtx,
  GenericActionCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
} from "convex/server";
import { DataModel } from "./dataModel";

export declare const query: QueryBuilder<DataModel, "public">;
export declare const internalQuery: QueryBuilder<DataModel, "internal">;
export declare const mutation: MutationBuilder<DataModel, "public">;
export declare const internalMutation: MutationBuilder<DataModel, "internal">;
export declare const action: ActionBuilder<DataModel, "public">;
export declare const internalAction: ActionBuilder<DataModel, "internal">;
export declare const httpAction: HttpActionBuilder;

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;
export type DatabaseReader = GenericDatabaseReader<DataModel>;
export type DatabaseWriter = GenericDatabaseWriter<DataModel>;
